version: '3'

volumes:
  keycloak-postgres:
      external: true
      name: keycloak_keycloak-postgres

networks:
  cloudbuild:
    # driver: overlay
    external: true
    

services:
  keycloak-postgres:
      image: postgres:14-alpine
      container_name: keycloak-postgres
      restart: always
      networks:
            - cloudbuild
      environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: keycloak
          POSTGRES_PASSWORD: keycloak_not_123
      volumes:
        - 'keycloak-postgres:/var/lib/postgresql/data'

  keycloak:
      image: quay.io/keycloak/keycloak:26.0.1
      container_name: keycloak
      restart: always
      networks:
        - cloudbuild
      env_file:
        - ../keycloak/.env
      depends_on:
        - keycloak-postgres
      command: start-dev
      ports:
        - 8889:8080